# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
      - name: Build Quartz for GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: konstfish/quartz-build-action@f15402f8aff68dd71509a6ef889c81fbaee531f5
        uses: konstfish/quartz-build-action@v6
        with:
          # The directory to build from
          source: # default is ./
          # The directory to write output into
          destination: # optional, default is ./_site
          # Title of resulting Quartz Page
          page_title: # optional, default is Quartz
          # Base URL (Required when setting icon or banner)
          page_base_url: # optional, default is example.com
          # Path to custom Quartz config file
          quartz_config: # optional
          # Path to custom Quartz layout file
          quartz_layout: # optional
          # Path to custom Quartz Page icon (png)
          quartz_icon: # optional
          # Path to custom Quartz Page banner (png)
          quartz_banner: # optional
          # Path to custom Quartz Page css
          quartz_custom_css: # optional
